// src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import Swal from 'sweetalert2'; // Agrega esta línea

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div class="min-h-screen flex items-center justify-center bg-background py-12 px-4 sm:px-6 lg:px-8">
      <div class="max-w-md w-full space-y-8">
        <div>
          <h2 class="mt-6 text-center text-3xl font-extrabold text-primary">
            Iniciar Sesión
          </h2>
        </div>
        <form class="mt-8 space-y-6" (ngSubmit)="onSubmit()">
          <div class="rounded-md shadow-sm -space-y-px">
            <div>
              <label for="email" class="sr-only">Correo electrónico</label>
              <input id="email" name="email" type="email" required
                class="appearance-none rounded-none relative block w-full px-3 py-2 border border-text placeholder-text text-primary rounded-t-md focus:outline-none focus:ring-secondary focus:border-secondary focus:z-10 sm:text-sm"
                placeholder="Correo electrónico" [(ngModel)]="email">
            </div>
            <div>
              <label for="password" class="sr-only">Contraseña</label>
              <input id="password" name="password" type="password" required
                class="appearance-none rounded-none relative block w-full px-3 py-2 border border-text placeholder-text text-primary rounded-b-md focus:outline-none focus:ring-secondary focus:border-secondary focus:z-10 sm:text-sm"
                placeholder="Contraseña" [(ngModel)]="password">
            </div>
          </div>

          <div>
            <button type="submit"
              class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-background bg-secondary hover:bg-accent focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-secondary">
              Iniciar Sesión
            </button>
          </div>
        </form>
        <div class="text-center">
          <a routerLink="/registro" class="font-medium text-secondary hover:text-accent">
            ¿No tienes una cuenta? Regístrate aquí
          </a>
        </div>
      </div>
    </div>
  `,
  styles: [`
    :host {
      display: block;
      font-family: var(--font-body-family);
    }

    h2 {
      font-family: var(--font-title-family);
      font-size: var(--font-title-size);
      font-weight: var(--font-title-weight);
    }

    input {
      font-family: var(--font-body-family);
      font-size: var(--font-body-size);
    }

    button {
      font-family: var(--font-body-family);
      font-size: var(--font-body-size);
      font-weight: var(--font-body-weight);
    }

    a {
      font-family: var(--font-body-family);
      font-size: var(--font-body-size);
    }
  `]
})
export class LoginComponent {
  email: string = '';
  password: string = '';

  constructor(private router: Router) {}

  async onSubmit() {
    const token = localStorage.getItem('token') || '';
    console.log('Token:', token);
    try {
      const res = await fetch('/admin-auth/login', {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${token}`
        },
        body: JSON.stringify({ email: this.email, password: this.password })
      });
      const data = await res.json();
      if (!res.ok) {
        Swal.fire({
          icon: 'error',
          title: 'Error',
          text: data.error?.error || data.error || JSON.stringify(data)
        });
        return;
      }
      localStorage.setItem('token', data.token);
      localStorage.setItem('email', data.email);
      await Swal.fire({
        icon: 'success',
        title: 'Login exitoso',
        text: 'Has iniciado sesión correctamente.'
      });
      this.router.navigate(['/personalization']);
    } catch (e) {
      Swal.fire({
        icon: 'error',
        title: 'Error',
        text: 'Error de red o del servidor'
      });
    }
  }
}

// src/views/Login.vue
<script setup lang="ts">

import { ref } from 'vue';
import { useRouter } from 'vue-router';
import Swal from 'sweetalert2';

const email = ref('');
const password = ref('');
const router = useRouter();

const onSubmit = async (e: Event) => {
  e.preventDefault();
  const token = localStorage.getItem('token') || '';
  try {
    const res = await fetch('/admin-auth/login', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({ email: email.value, password: password.value })
    });
    const data = await res.json();
    if (!res.ok) {
      // Si el error es por usuario deshabilitado
      if (data.error && typeof data.error === 'string' && data.error.toLowerCase().includes('inactive')) {
        await Swal.fire({
          icon: 'error',
          title: 'Usuario deshabilitado',
          text: 'Su usuario ha sido deshabilitado, por favor contacte con un administrador.'
        });
        return;
      }
      await Swal.fire({
        icon: 'error',
        title: 'Error',
        text: data.error?.error || data.error || JSON.stringify(data)
      });
      return;
    }
    // Si el usuario está inactivo, aunque el backend no lo bloquee
    if (data.status && data.status === 'inactive') {
      await Swal.fire({
        icon: 'error',
        title: 'Usuario deshabilitado',
        text: 'Su usuario ha sido deshabilitado, por favor contacte con un administrador.'
      });
      return;
    }
    localStorage.setItem('token', data.token);
    localStorage.setItem('email', data.email);
    localStorage.setItem('type', data.type);
    await Swal.fire({
      icon: 'success',
      title: 'Login exitoso',
      text: 'Has iniciado sesión correctamente.'
    });
    router.push('/personalization');
  } catch (e) {
    await Swal.fire({
      icon: 'error',
      title: 'Error',
      text: 'Error de red o del servidor'
    });
  }
};
</script>

<template>
  <div class="login-container">
    <div class="login-card">
      <h1 class="login-title">Iniciar Sesión</h1>
      <form class="login-form" @submit="onSubmit">
        <div class="form-group">
          <label for="email" class="form-label">Correo Electrónico</label>
          <input 
            type="email" 
            id="email" 
            class="form-input" 
            placeholder="tu@email.com"
            required
            v-model="email"
          >
        </div>
        <div class="form-group">
          <label for="password" class="form-label">Contraseña</label>
          <input 
            type="password" 
            id="password" 
            class="form-input" 
            placeholder="Tu contraseña"
            required
            v-model="password"
          >
        </div>
        <button type="submit" class="login-button">
          Iniciar Sesión
        </button>
      </form>
    </div>
  </div>
</template>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: var(--color-background);
  padding: 1rem;
}

.login-card {
  background: white;
  padding: 2rem;
  border-radius: 12px;
  box-shadow: 0 8px 32px rgb(from var(--color-primary) r g b / 0.15);
  width: 100%;
  max-width: 400px;
}

.login-title {
  font-family: var(--font-title-family);
  font-size: var(--font-title-size);
  font-weight: var(--font-title-weight);
  color: var(--font-title-color);
  text-align: center;
  margin-bottom: 2rem;
}

.login-form {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
}

.form-group {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.form-label {
  font-family: var(--font-paragraph-family);
  font-size: var(--font-paragraph-size);
  color: var(--font-paragraph-color);
  font-weight: 600;
}

.form-input {
  padding: 0.75rem;
  border: 2px solid var(--color-background);
  border-radius: 8px;
  font-family: var(--font-body-family);
  font-size: var(--font-body-size);
  color: var(--font-body-color);
  transition: border-color 0.3s ease;
}

.form-input:focus {
  outline: none;
  border-color: var(--color-secondary);
}

.form-input::placeholder {
  color: var(--color-text);
  opacity: 0.7;
}

.login-button {
  background-color: var(--color-primary);
  color: white;
  border: none;
  padding: 0.75rem;
  border-radius: 8px;
  font-family: var(--font-paragraph-family);
  font-size: var(--font-paragraph-size);
  font-weight: 600;
  cursor: pointer;
  transition: background-color 0.3s ease;
  margin-top: 1rem;
}

.login-button:hover {
  background-color: var(--color-secondary);
}

@media (max-width: 480px) {
  .login-card {
    padding: 1.5rem;
  }
  
  .login-title {
    font-size: 2rem;
  }
}
</style>
