// src/App.tsx
import React from 'react';
import RoutesList from './router';

const App: React.FC = () => {
  return (
    <>
      <header>
        <div className="wrapper">
          <nav>
            {/* Aquí podría ir una barra de navegación */}
          </nav>
        </div>
      </header>
      <RoutesList />
    </>
  );
};

export default App;

// src/App.vue
<script setup lang="ts">
import { RouterView } from 'vue-router'
</script>

<template>
  <header>
    <div class="wrapper">
      <nav>
        <!-- Aquí podría ir una barra de navegación -->
      </nav>
    </div>
  </header>

  <RouterView />
</template>

<style scoped>
/* Estilos para App.vue */
</style>
